export interface GameWord {
  word: string;
  hint: string;
}

export const gameWords: GameWord[] = [
  // Orte
  { word: "Krankenhaus", hint: "Arzt" },
  { word: "Supermarkt", hint: "Einkaufen" },
  { word: "Schule", hint: "Lehrer" },
  { word: "Restaurant", hint: "Kellner" },
  { word: "Flughafen", hint: "Flugzeug" },
  { word: "Bibliothek", hint: "Bücher" },
  { word: "Kino", hint: "Film" },
  { word: "Kirche", hint: "Priester" },
  { word: "Fitnessstudio", hint: "Training" },
  { word: "Friseur", hint: "Haare" },
  { word: "Zoo", hint: "Tiere" },
  { word: "Bahnhof", hint: "Zug" },
  { word: "Polizeiwache", hint: "Polizist" },
  { word: "Feuerwache", hint: "Feuerwehrmann" },
  { word: "Apotheke", hint: "Medikamente" },
  { word: "Zahnarzt", hint: "Zähne" },
  { word: "Bank", hint: "Geld" },
  { word: "Gefängnis", hint: "Verbrecher" },
  { word: "Museum", hint: "Geschichte" },
  { word: "Theater", hint: "Schauspiel" },

  // Berufe
  { word: "Programmierer", hint: "Code" },
  { word: "Ingenieur", hint: "Konstruktion" },
  { word: "Architekt", hint: "Gebäude" },
  { word: "Elektriker", hint: "Strom" },
  { word: "Klempner", hint: "Wasser" },
  { word: "Gärtner", hint: "Pflanzen" },
  { word: "Koch", hint: "Essen" },
  { word: "Bäcker", hint: "Brot" },
  { word: "Metzger", hint: "Fleisch" },
  { word: "Schneider", hint: "Kleidung" },
  { word: "Fahrer", hint: "Auto" },
  { word: "Pilot", hint: "Flugzeug" },
  { word: "Kapitän", hint: "Schiff" },
  { word: "Farmer", hint: "Landwirtschaft" },
  { word: "Bergsteiger", hint: "Berg" },
  { word: "Taucher", hint: "Wasser" },
  { word: "Astronaut", hint: "Weltall" },
  { word: "Detektiv", hint: "Mystery" },
  { word: "Anwalt", hint: "Gesetz" },
  { word: "Reporter", hint: "Nachrichten" },

  // Tiere
  { word: "Löwe", hint: "König der Tiere" },
  { word: "Elefant", hint: "Rüssel" },
  { word: "Giraffe", hint: "Langer Hals" },
  { word: "Zebra", hint: "Streifen" },
  { word: "Panda", hint: "Bambus" },
  { word: "Polar", hint: "Eis" },
  { word: "Affe", hint: "Banane" },
  { word: "Adler", hint: "Flug" },
  { word: "Fisch", hint: "Wasser" },
  { word: "Schlange", hint: "Giftig" },
  { word: "Schildkröte", hint: "Langsam" },
  { word: "Pinguin", hint: "Antarktis" },
  { word: "Kamele", hint: "Wüste" },
  { word: "Hirsch", hint: "Geweih" },
  { word: "Wal", hint: "Meer" },
  { word: "Delfin", hint: "Intelligent" },
  { word: "Rabe", hint: "Schwarz" },
  { word: "Schmetterling", hint: "Flügel" },
  { word: "Biene", hint: "Honig" },
  { word: "Spinne", hint: "Netz" },

  // Essen & Trinken
  { word: "Pizza", hint: "Italien" },
  { word: "Spaghetti", hint: "Nudel" },
  { word: "Burger", hint: "Patty" },
  { word: "Kartoffel", hint: "Stärke" },
  { word: "Tomate", hint: "Rot" },
  { word: "Käse", hint: "Molkerei" },
  { word: "Schokolade", hint: "Süß" },
  { word: "Keks", hint: "Knusprig" },
  { word: "Kuchen", hint: "Geburtstag" },
  { word: "Eis", hint: "Kalt" },
  { word: "Milch", hint: "Kuh" },
  { word: "Kaffee", hint: "Wach" },
  { word: "Tee", hint: "Heiß" },
  { word: "Saft", hint: "Orange" },
  { word: "Bier", hint: "Alkohol" },
  { word: "Wein", hint: "Traube" },
  { word: "Apfel", hint: "Rot" },
  { word: "Banane", hint: "Gelb" },
  { word: "Kirsche", hint: "Klein" },
  { word: "Wassermelone", hint: "Sommer" },

  // Gegenstände
  { word: "Telefon", hint: "Anruf" },
  { word: "Computer", hint: "Bildschirm" },
  { word: "Laptop", hint: "Tragbar" },
  { word: "Uhr", hint: "Zeit" },
  { word: "Brieftasche", hint: "Geld" },
  { word: "Schlüssel", hint: "Tür" },
  { word: "Tasche", hint: "Gepäck" },
  { word: "Schuhe", hint: "Fuß" },
  { word: "Hut", hint: "Kopf" },
  { word: "Brille", hint: "Auge" },
  { word: "Uhr", hint: "Handgelenk" },
  { word: "Ring", hint: "Finger" },
  { word: "Halskette", hint: "Hals" },
  { word: "Buch", hint: "Seite" },
  { word: "Stift", hint: "Schreiben" },
  { word: "Papier", hint: "Blatt" },
  { word: "Lampe", hint: "Licht" },
  { word: "Tische", hint: "Möbel" },
  { word: "Stuhl", hint: "Sitzen" },
  { word: "Bett", hint: "Schlaf" },

  // Natur & Wetter
  { word: "Berg", hint: "Hoch" },
  { word: "Fluss", hint: "Wasser fließt" },
  { word: "Wald", hint: "Baum" },
  { word: "Strand", hint: "Sand" },
  { word: "Meer", hint: "Salzwasser" },
  { word: "See", hint: "Süßwasser" },
  { word: "Insel", hint: "Wasser umgeben" },
  { word: "Busch", hint: "Kraut" },
  { word: "Blume", hint: "Bunt" },
  { word: "Regen", hint: "Nass" },
  { word: "Schnee", hint: "Weiß" },
  { word: "Wind", hint: "Luft" },
  { word: "Blitz", hint: "Donnerstag" },
  { word: "Regenbogen", hint: "Farben" },
  { word: "Nebel", hint: "Grau" },
  { word: "Wolke", hint: "Himmel" },
  { word: "Sonne", hint: "Gelb" },
  { word: "Mond", hint: "Nacht" },
  { word: "Stern", hint: "Funkeln" },
  { word: "Komet", hint: "Weltall" },

  // Aktivitäten & Sport
  { word: "Fußball", hint: "Tor" },
  { word: "Basketball", hint: "Korb" },
  { word: "Tennis", hint: "Schläger" },
  { word: "Schwimmen", hint: "Pool" },
  { word: "Laufen", hint: "Jogging" },
  { word: "Radfahren", hint: "Fahrrad" },
  { word: "Skifahren", hint: "Berg Schnee" },
  { word: "Surfen", hint: "Welle" },
  { word: "Tanzen", hint: "Musik" },
  { word: "Singen", hint: "Stimme" },
  { word: "Malen", hint: "Kunst" },
  { word: "Zeichnen", hint: "Stift" },
  { word: "Fotografieren", hint: "Kamera" },
  { word: "Gamen", hint: "Konsole" },
  { word: "Klettern", hint: "Hoch" },
  { word: "Springen", hint: "Luft" },
  { word: "Boxen", hint: "Faust" },
  { word: "Reiten", hint: "Pferd" },
  { word: "Wandern", hint: "Zu Fuß" },
  { word: "Campen", hint: "Zelt" },

  // Farben
  { word: "Rot", hint: "Liebe" },
  { word: "Blau", hint: "Himmel" },
  { word: "Gelb", hint: "Sonne" },
  { word: "Grün", hint: "Grass" },
  { word: "Orange", hint: "Frucht" },
  { word: "Violett", hint: "Lila" },
  { word: "Rosa", hint: "Hell Rot" },
  { word: "Braun", hint: "Erde" },
  { word: "Schwarz", hint: "Dunkel" },
  { word: "Weiß", hint: "Hell" },
  { word: "Grau", hint: "Mitte" },
  { word: "Gold", hint: "Wertvoll" },
  { word: "Silber", hint: "Glänzend" },
  { word: "Türkis", hint: "Meer" },
  { word: "Purpur", hint: "König" },

  // Länder & Orte
  { word: "Deutschland", hint: "Schnitzel" },
  { word: "Italien", hint: "Pizza" },
  { word: "Frankreich", hint: "Paris" },
  { word: "Japan", hint: "Sushi" },
  { word: "Ägypten", hint: "Pyramide" },
  { word: "Brasilien", hint: "Karneval" },
  { word: "Kanada", hint: "Biber" },
  { word: "Australien", hint: "Känguru" },
  { word: "Indien", hint: "Taj Mahal" },
  { word: "Spanien", hint: "Flamenco" },
  { word: "Griechenland", hint: "Antike" },
  { word: "Schweden", hint: "IKEA" },
  { word: "Norwegen", hint: "Fjord" },
  { word: "Russland", hint: "Groß" },
  { word: "China", hint: "Mauer" },
  { word: "Amerika", hint: "Vereinigt" },
  { word: "England", hint: "Königin" },
  { word: "Irland", hint: "Grün" },
  { word: "Portugal", hint: "Wein" },
  { word: "Türkei", hint: "Istanbul" },

  // Märchen & Mythologie
  { word: "Drache", hint: "Feuer" },
  { word: "Prinzessin", hint: "Krone" },
  { word: "König", hint: "Thron" },
  { word: "Hexe", hint: "Zauber" },
  { word: "Zauberer", hint: "Stab" },
  { word: "Schatz", hint: "Gold" },
  { word: "Schwert", hint: "Waffe" },
  { word: "Schild", hint: "Schutz" },
  { word: "Kreatur", hint: "Monster" },
  { word: "Riese", hint: "Groß" },
  { word: "Zwerg", hint: "Klein" },
  { word: "Elf", hint: "Magisch" },
  { word: "Vampir", hint: "Nacht" },
  { word: "Zombie", hint: "Tot" },
  { word: "Geist", hint: "Übernatürlich" },

  // Musik & Kunst
  { word: "Gitarre", hint: "Saite" },
  { word: "Klavier", hint: "Tasten" },
  { word: "Trompete", hint: "Bläser" },
  { word: "Trommel", hint: "Rhythmus" },
  { word: "Violine", hint: "Bogen" },
  { word: "Flöte", hint: "Holz" },
  { word: "Harfe", hint: "Engel" },
  { word: "Mikrofon", hint: "Singen" },
  { word: "Lautsprecher", hint: "Ton" },
  { word: "Kunstwerk", hint: "Galerie" },
  { word: "Statue", hint: "Stein" },
  { word: "Gemälde", hint: "Leinwand" },
  { word: "Skulptur", hint: "Form" },
  { word: "Mosaik", hint: "Fliese" },
  { word: "Keramik", hint: "Ton" },

  // Wissenschaft
  { word: "Atom", hint: "Klein" },
  { word: "Elektron", hint: "Ladung" },
  { word: "Molekül", hint: "Partikel" },
  { word: "Chemie", hint: "Reaktion" },
  { word: "Biologie", hint: "Leben" },
  { word: "Physik", hint: "Kraft" },
  { word: "Mathematik", hint: "Zahlen" },
  { word: "Astronomie", hint: "Stern" },
  { word: "Geologie", hint: "Felsen" },
  { word: "Botanik", hint: "Pflanze" },
  { word: "Zoologie", hint: "Tier" },
  { word: "Mikroskop", hint: "Vergrößerung" },
  { word: "Teleskop", hint: "Fern" },
  { word: "Labor", hint: "Experiment" },
  { word: "Formel", hint: "Gleichung" },

  // Mode & Kleidung
  { word: "Hemd", hint: "Oben" },
  { word: "Hose", hint: "Unten" },
  { word: "Kleid", hint: "Feminin" },
  { word: "Rock", hint: "Kurz" },
  { word: "Jacke", hint: "Warm" },
  { word: "Mantel", hint: "Lang" },
  { word: "Handschuhe", hint: "Hand" },
  { word: "Schal", hint: "Hals" },
  { word: "Socken", hint: "Fuß" },
  { word: "Unterwäsche", hint: "Darunter" },
  { word: "Badeanzug", hint: "Strand" },
  { word: "Pyjama", hint: "Schlaf" },
  { word: "Anzug", hint: "Formal" },
  { word: "Krawatte", hint: "Hals Formal" },
  { word: "Gürtel", hint: "Taille" },

  // Verkehr & Fahrzeuge
  { word: "Auto", hint: "Straße" },
  { word: "Fahrrad", hint: "Pedal" },
  { word: "Motorrad", hint: "Schnell" },
  { word: "Lastwagen", hint: "Cargo" },
  { word: "Autobus", hint: "Viele Menschen" },
  { word: "Zug", hint: "Schiene" },
  { word: "Flugzeug", hint: "Luft" },
  { word: "Hubschrauber", hint: "Propeller" },
  { word: "Schiff", hint: "Meer" },
  { word: "Boot", hint: "Klein" },
  { word: "U-Boot", hint: "Unter Wasser" },
  { word: "Rakete", hint: "Weltall" },
  { word: "Bagger", hint: "Erde" },
  { word: "Betonmischer", hint: "Baustelle" },
  { word: "Feuerwehrauto", hint: "Brandbekämpfung" },

  // Bildung
  { word: "Lehrer", hint: "Klasse" },
  { word: "Student", hint: "Universität" },
  { word: "Schüler", hint: "Grundschule" },
  { word: "Professor", hint: "Höher" },
  { word: "Klasse", hint: "Schüler" },
  { word: "Prüfung", hint: "Test" },
  { word: "Vorlesung", hint: "Hörsaal" },
  { word: "Tafel", hint: "Kreide" },
  { word: "Bücher", hint: "Lesen" },
  { word: "Noten", hint: "Bewertung" },
  { word: "Alphabetisierung", hint: "Lesen Schreiben" },
  { word: "Mathematik", hint: "Zahlen" },
  { word: "Naturwissenschaft", hint: "Labor" },
  { word: "Geschichte", hint: "Vergangenheit" },
  { word: "Geographie", hint: "Land" },

  // Familie & Beziehungen
  { word: "Mutter", hint: "Elternteil weiblich" },
  { word: "Vater", hint: "Elternteil männlich" },
  { word: "Bruder", hint: "Junge Sibling" },
  { word: "Schwester", hint: "Mädchen Sibling" },
  { word: "Großmutter", hint: "Großeltern weiblich" },
  { word: "Großvater", hint: "Großeltern männlich" },
  { word: "Onkel", hint: "Familie männlich" },
  { word: "Tante", hint: "Familie weiblich" },
  { word: "Cousin", hint: "Familie männlich" },
  { word: "Cousine", hint: "Familie weiblich" },
  { word: "Ehemann", hint: "Verheiratet männlich" },
  { word: "Ehefrau", hint: "Verheiratet weiblich" },
  { word: "Sohn", hint: "Kind männlich" },
  { word: "Tochter", hint: "Kind weiblich" },
  { word: "Baby", hint: "Säugling" },

  // Häusliche Gegenstände
  { word: "Kühlschrank", hint: "Kalt" },
  { word: "Ofen", hint: "Backen" },
  { word: "Herd", hint: "Kochen" },
  { word: "Geschirrspüler", hint: "Teller" },
  { word: "Waschmaschine", hint: "Kleidung" },
  { word: "Trockner", hint: "Trocken" },
  { word: "Mikrowelle", hint: "Schnell" },
  { word: "Toaster", hint: "Brot" },
  { word: "Wasserkocher", hint: "Heiß Wasser" },
  { word: "Mixer", hint: "Mischen" },
  { word: "Sofa", hint: "Sitzen" },
  { word: "Regal", hint: "Lagerung" },
  { word: "Spiegel", hint: "Reflexion" },
  { word: "Vorhang", hint: "Fenster" },
  { word: "Teppich", hint: "Boden" },

  // Körperteile
  { word: "Kopf", hint: "Oben" },
  { word: "Hals", hint: "Verbindung" },
  { word: "Schulter", hint: "Oben Arm" },
  { word: "Arm", hint: "Gliedmaße" },
  { word: "Ellebogen", hint: "Biegung Arm" },
  { word: "Unterarm", hint: "Unterhalb Ellebogen" },
  { word: "Handgelenk", hint: "Hand Arm" },
  { word: "Hand", hint: "Finger" },
  { word: "Finger", hint: "Hand" },
  { word: "Brust", hint: "Herz" },
  { word: "Bauch", hint: "Magen" },
  { word: "Rücken", hint: "Hinter" },
  { word: "Hüfte", hint: "Mittelteil" },
  { word: "Bein", hint: "Gliedmaße" },
  { word: "Knie", hint: "Biegung Bein" },
  { word: "Knöchel", hint: "Bein Fuß" },
  { word: "Fuß", hint: "Unten" },
  { word: "Zehe", hint: "Fuß" },
  { word: "Auge", hint: "Sehen" },
  { word: "Ohr", hint: "Hören" },
  { word: "Nase", hint: "Riechen" },
  { word: "Mund", hint: "Essen" },
  { word: "Zahn", hint: "Kauen" },
  { word: "Zunge", hint: "Schmecken" },
  { word: "Lip", hint: "Mund" },
  { word: "Haut", hint: "Bedeckung" },
  { word: "Blut", hint: "Rot" },
  { word: "Knochen", hint: "Struktur" },
  { word: "Muskel", hint: "Kraft" },
  { word: "Gehirn", hint: "Denken" },

  // Gefühle & Emotionen
  { word: "Glück", hint: "Freude" },
  { word: "Trauer", hint: "Leid" },
  { word: "Liebe", hint: "Zuneigung" },
  { word: "Hass", hint: "Ablehnung" },
  { word: "Angst", hint: "Furcht" },
  { word: "Hoffnung", hint: "Optimismus" },
  { word: "Hoffnungslosigkeit", hint: "Pessimismus" },
  { word: "Langeweile", hint: "Tedium" },
  { word: "Wut", hint: "Zorn" },
  { word: "Freundlichkeit", hint: "Güte" },
  { word: "Eifersucht", hint: "Neid" },
  { word: "Verlegenheit", hint: "Scham" },
  { word: "Erregung", hint: "Aufregung" },
  { word: "Beruhigung", hint: "Frieden" },
  { word: "Verwirrung", hint: "Verwirrung" },

  // Jahreszeiten & Zeit
  { word: "Frühling", hint: "Blüte" },
  { word: "Sommer", hint: "Heiß" },
  { word: "Herbst", hint: "Fall" },
  { word: "Winter", hint: "Schnee" },
  { word: "Januar", hint: "Neu Jahr" },
  { word: "Februar", hint: "Valentinstag" },
  { word: "März", hint: "Frühling" },
  { word: "April", hint: "Dusche" },
  { word: "Mai", hint: "Frühling" },
  { word: "Juni", hint: "Sommer" },
  { word: "Juli", hint: "Mittsommer" },
  { word: "August", hint: "Sommer" },
  { word: "September", hint: "Herbst" },
  { word: "Oktober", hint: "Halloween" },
  { word: "November", hint: "Herbst" },
  { word: "Dezember", hint: "Weihnachten" },
  { word: "Montag", hint: "Wochentag" },
  { word: "Dienstag", hint: "Wochentag" },
  { word: "Mittwoch", hint: "Mitte" },
  { word: "Donnerstag", hint: "Wochentag" },
  { word: "Freitag", hint: "Wochenende" },
  { word: "Samstag", hint: "Wochenende" },
  { word: "Sonntag", hint: "Ruhe" },

  // Feste & Feiertage
  { word: "Weihnachten", hint: "Dezember" },
  { word: "Ostern", hint: "Hase" },
  { word: "Neujahr", hint: "Januar" },
  { word: "Valentinstag", hint: "Liebe" },
  { word: "Halloween", hint: "Kürbis" },
  { word: "Dankbarkeit", hint: "Truthahn" },
  { word: "Hochzeit", hint: "Verheiratung" },
  { word: "Taufe", hint: "Baby" },
  { word: "Geburtstag", hint: "Kuchen" },
  { word: "Jahrestag", hint: "Erinnerung" },
  { word: "Karneval", hint: "Maske" },
  { word: "Silvester", hint: "Countdown" },
  { word: "Muttertag", hint: "Mutter" },
  { word: "Vatertag", hint: "Vater" },
  { word: "Lehrertag", hint: "Lehrer" },

  // Nützliche Gegenstände
  { word: "Hammer", hint: "Nagel" },
  { word: "Schraubenzieher", hint: "Schraube" },
  { word: "Säge", hint: "Schneiden" },
  { word: "Zange", hint: "Greifen" },
  { word: "Bohrer", hint: "Loch" },
  { word: "Leitern", hint: "Hoch" },
  { word: "Seil", hint: "Fest" },
  { word: "Nagel", hint: "Holz" },
  { word: "Schraube", hint: "Drehen" },
  { word: "Bolzen", hint: "Halt" },
  { word: "Klammern", hint: "Sichern" },
  { word: "Leim", hint: "Kleben" },
  { word: "Band", hint: "Kleben" },
  { word: "Klebstoff", hint: "Haften" },
  { word: "Farbe", hint: "Farbton" },
   { word: "Krankenhaus", hint: "Nachtschicht" },
  { word: "Supermarkt", hint: "Regalgänge" },
  { word: "Schule", hint: "Pausenklingel" },
  { word: "Restaurant", hint: "Reservierung" },
  { word: "Flughafen", hint: "Sicherheitskontrolle" },
  { word: "Bibliothek", hint: "Flüstern" },
  { word: "Kino", hint: "Popcorn" },
  { word: "Kirche", hint: "Bänke" },
  { word: "Fitnessstudio", hint: "Mitgliedschaft" },
  { word: "Friseur", hint: "Termin" },
  { word: "Zoo", hint: "Gehege" },
  { word: "Bahnhof", hint: "Anzeigetafel" },
  { word: "Polizeiwache", hint: "Protokoll" },
  { word: "Feuerwache", hint: "Alarm" },
  { word: "Apotheke", hint: "Rezept" },
  { word: "Zahnarzt", hint: "Bohrer" },
  { word: "Bank", hint: "Schalter" },
  { word: "Gefängnis", hint: "Zellen" },
  { word: "Museum", hint: "Ausstellung" },
  { word: "Theater", hint: "Premiere" },

  // Berufe
  { word: "Programmierer", hint: "Dark Mode" },
  { word: "Ingenieur", hint: "Prototyp" },
  { word: "Architekt", hint: "Grundriss" },
  { word: "Elektriker", hint: "Sicherung" },
  { word: "Klempner", hint: "Leitung" },
  { word: "Gärtner", hint: "Gießkanne" },
  { word: "Koch", hint: "Mise en Place" },
  { word: "Bäcker", hint: "Teigruhe" },
  { word: "Metzger", hint: "Schneidebrett" },
  { word: "Schneider", hint: "Maßband" },
  { word: "Fahrer", hint: "Schichtplan" },
  { word: "Pilot", hint: "Cockpit" },
  { word: "Kapitän", hint: "Brücke" },
  { word: "Farmer", hint: "Ernte" },
  { word: "Bergsteiger", hint: "Seilschaft" },
  { word: "Taucher", hint: "Flasche" },
  { word: "Astronaut", hint: "Schwerkraft" },
  { word: "Detektiv", hint: "Indizien" },
  { word: "Anwalt", hint: "Akten" },
  { word: "Reporter", hint: "Interview" },

  // Tiere
  { word: "Löwe", hint: "Savanne" },
  { word: "Elefant", hint: "Herde" },
  { word: "Giraffe", hint: "Baumkronen" },
  { word: "Zebra", hint: "Herdenpanik" },
  { word: "Panda", hint: "Schlafrhythmus" },
  { word: "Pinguin", hint: "Kolonie" },
  { word: "Fuchs", hint: "Listig" },
  { word: "Eule", hint: "Nachtaktiv" },
  { word: "Hai", hint: "Flosse" },
  { word: "Schlange", hint: "Häutung" },
  { word: "Schildkröte", hint: "Panzer" },
  { word: "Delfin", hint: "Sprung" },
  { word: "Rabe", hint: "Aas" },
  { word: "Schmetterling", hint: "Metamorphose" },
  { word: "Biene", hint: "Schwarm" },
  { word: "Spinne", hint: "Ecke" },
  { word: "Wolf", hint: "Rudel" },
  { word: "Eichhörnchen", hint: "Versteck" },
  { word: "Kamel", hint: "Karawane" },
  { word: "Krake", hint: "Tentakel" },

  // Essen & Trinken
  { word: "Pizza", hint: "Lieferdienst" },
  { word: "Spaghetti", hint: "Gabel" },
  { word: "Burger", hint: "Drive-in" },
  { word: "Kartoffel", hint: "Beilage" },
  { word: "Käse", hint: "Reifung" },
  { word: "Schokolade", hint: "Tafel" },
  { word: "Keks", hint: "Krümel" },
  { word: "Kuchen", hint: "Form" },
  { word: "Eis", hint: "Kugel" },
  { word: "Kaffee", hint: "Bohnen" },
  { word: "Tee", hint: "Aufguss" },
  { word: "Saft", hint: "Fruchtpressen" },
  { word: "Bier", hint: "Zapfhahn" },
  { word: "Wein", hint: "Keller" },
  { word: "Apfel", hint: "Kerngehäuse" },
  { word: "Banane", hint: "Schale" },
  { word: "Wassermelone", hint: "Kerne" },
  { word: "Reis", hint: "Beilage" },
  { word: "Döner", hint: "Drehspieß" },
  { word: "Sushi", hint: "Stäbchen" },

  // Trend / Jugendsprache (als Wörter)
  { word: "Cringe", hint: "Fremdscham" },
  { word: "Lost", hint: "Planlos" },
  { word: "Macher", hint: "Durchziehen" },
  { word: "Goofy", hint: "Tollpatschig" },
  { word: "Sus", hint: "Verdächtig" },
  { word: "Aura", hint: "Ausstrahlung" },
  { word: "Bodenlos", hint: "Unverschämt" },
  { word: "Delulu", hint: "Realitätsfern" },
  { word: "Ghosten", hint: "Chatverlauf" },
  { word: "Flexen", hint: "Angeben" },

  // Gegenstände
  { word: "Telefon", hint: "Klingeln" },
  { word: "Computer", hint: "Update" },
  { word: "Laptop", hint: "Akkustand" },
  { word: "Uhr", hint: "Zeiger" },
  { word: "Schlüssel", hint: "Bund" },
  { word: "Rucksack", hint: "Träger" },
  { word: "Schuhe", hint: "Sohle" },
  { word: "Brille", hint: "Gestell" },
  { word: "Stift", hint: "Kappe" },
  { word: "Papier", hint: "Rand" },
  { word: "Lampe", hint: "Schalter" },
  { word: "Stuhl", hint: "Lehne" },
  { word: "Bett", hint: "Lattenrost" },
  { word: "Fernseher", hint: "Fernbedienung" },
  { word: "Kopfhörer", hint: "Kabelsalat" },

  // Natur & Wetter
  { word: "Berg", hint: "Steigung" },
  { word: "Fluss", hint: "Strömung" },
  { word: "Wald", hint: "Laub" },
  { word: "Strand", hint: "Handtuch" },
  { word: "Meer", hint: "Salz" },
  { word: "See", hint: "Ufer" },
  { word: "Insel", hint: "Abgeschieden" },
  { word: "Blume", hint: "Blüte" },
  { word: "Regen", hint: "Pfützen" },
  { word: "Schnee", hint: "Spuren" },
  { word: "Wind", hint: "Böen" },
  { word: "Blitz", hint: "Sekunden zählen" },
  { word: "Regenbogen", hint: "nach dem Schauer" },
  { word: "Nebel", hint: "Sichtweite" },
  { word: "Sonne", hint: "Schatten" },
  { word: "Mond", hint: "Phase" },
  { word: "Stern", hint: "Sternbild" },
  { word: "Vulkan", hint: "Ausbruch" },
  { word: "Höhle", hint: "Fackel" },
  { word: "Wüste", hint: "Oase" },

  // Aktivitäten & Sport
  { word: "Fußball", hint: "Abseits" },
  { word: "Basketball", hint: "Dreipunktewurf" },
  { word: "Tennis", hint: "Aufschlag" },
  { word: "Schwimmen", hint: "Bahn" },
  { word: "Laufen", hint: "Pace" },
  { word: "Radfahren", hint: "Gangschaltung" },
  { word: "Skifahren", hint: "Lift" },
  { word: "Surfen", hint: "Brett" },
  { word: "Boxen", hint: "Runde" },
  { word: "Reiten", hint: "Sattel" },
  { word: "Wandern", hint: "Wegmarkierung" },
  { word: "Tanzen", hint: "Choreo" },
  { word: "Singen", hint: "Tonlage" },
  { word: "Gamen", hint: "Lobby" },
  { word: "Yoga", hint: "Matte" },

  // Länder & trendige Orte
  { word: "Deutschland", hint: "Pfandautomat" },
  { word: "Italien", hint: "Espressobar" },
  { word: "Frankreich", hint: "Baguette" },
  { word: "Japan", hint: "Konbini" },
  { word: "USA", hint: "Highway" },
  { word: "Türkei", hint: "Basar" },
  { word: "Spanien", hint: "Siesta" },
  { word: "Griechenland", hint: "Ruinen" },
  { word: "Dubai", hint: "Wolkenkratzer" },
  { word: "Island", hint: "Geysire" },

  // Digital & Social Media
  { word: "Instagram", hint: "Story" },
  { word: "TikTok", hint: "For You" },
  { word: "YouTube", hint: "Thumbnail" },
  { word: "Podcast", hint: "Kopfhörer" },
  { word: "Livestream", hint: "Chat" },
  { word: "Influencer", hint: "Kooperation" },
  { word: "Hashtag", hint: "Reichweite" },
  { word: "Algorithmus", hint: "Empfehlungen" },
  { word: "Meme", hint: "Template" },
  { word: "Emote", hint: "Twitch" },

  // Körperteile
  { word: "Kopf", hint: "Gedanken" },
  { word: "Schulter", hint: "Last" },
  { word: "Hand", hint: "Händedruck" },
  { word: "Finger", hint: "Abdruck" },
  { word: "Brust", hint: "Atmung" },
  { word: "Bauch", hint: "Knurren" },
  { word: "Rücken", hint: "Haltung" },
  { word: "Bein", hint: "Schritt" },
  { word: "Knie", hint: "Beugung" },
  { word: "Fuß", hint: "Abdruck" },
  { word: "Auge", hint: "Blick" },
  { word: "Ohr", hint: "Geräusch" },
  { word: "Nase", hint: "Duft" },
  { word: "Mund", hint: "Aussprache" },
  { word: "Zunge", hint: "Geschmack" },

  // Gefühle
  { word: "Glück", hint: "Timing" },
  { word: "Trauer", hint: "Schwere" },
  { word: "Liebe", hint: "Priorität" },
  { word: "Hass", hint: "Grenzen" },
  { word: "Angst", hint: "Adrenalin" },
  { word: "Eifersucht", hint: "Vergleich" },
  { word: "Motivation", hint: "Ziel" },
  { word: "Stress", hint: "Deadline" },
  { word: "Langeweile", hint: "Scrollen" },
  { word: "Stolz", hint: "Leistung" },

  // Zeit & Jahreszeiten
  { word: "Frühling", hint: "Allergie" },
  { word: "Sommer", hint: "Hitze" },
  { word: "Herbst", hint: "Laubhaufen" },
  { word: "Winter", hint: "Eiskratzen" },
  { word: "Montag", hint: "Startschwierigkeiten" },
  { word: "Freitag", hint: "Feierabend" },
  { word: "Sonntag", hint: "Ruhemodus" },
  { word: "Neujahr", hint: "Vorsätze" },
  { word: "Weihnachten", hint: "Geschenkpapier" },
  { word: "Geburtstag", hint: "Kerzen" },
];